#!/bin/bash

# if we there is a config in the mounted volume, use that!
if [ -e /vagrant/prod_config.py ]; then
  echo "Using the prod_config.py from /vagrant/prod_config.py"
  cp -f /vagrant/prod_config.py /app/ADSWorker/local_config.py
fi

# on every restart check/deploy latest version
/gitpull.sh

cd /app

# start the pipeline
python run.py -p
